### ISSUE TITLE
DL's versus Form's?

### ISSUE THREAD

**Issue by ShaydeNofziger** [blackbaud-community/BBIS-Advanced-Donation-Form#1]
Is there any particular reason why input fields are contained in dl tags versus forms? Users using accessibility software may run into issues, as dl are description lists (definition lists pre-HTML 5).

**Comment by Blackbaud-BobbyEarl** [comment]
DL's were used simply because it's a small tag that renders well without any CSS.  I would encourage better semantic markup (unrelated to the Advanced Donation Form) when using any HTML in production.
